### ISSUE TITLE
Add gogs support

### ISSUE THREAD

**Issue by guyzmo** [guyzmo/git-repo#18]

**Comment by pyhedgehog** [comment]
If there are no objections I'm going to implement this one.

**Comment by guyzmo** [comment]
I got no objections, don't hesitate to ask for my help on anything. I wanted to work on it recently, as I started pushing to a friend's gogs, but I already got my hands full with both the gitlab and bitbucket integrations.
I'm also available on freenode on the channel #git-repo so please come and never hesitate to discuss the project.

**Comment by pyhedgehog** [comment]
@guyzmo, I have first version of code.
I have a question:
How I'm supposed to implement tests? Current tests (for other services) not working in my environment...

**Comment by guyzmo** [comment]
for the tests, @pyhedgehog, please come back on IRC so we can discuss quickly what's going wrong.

**Comment by pyhedgehog** [comment]
Just to log here results of our discussion:
 1. New version of PR should use third-party library (possibly [gogs-client](https://pypi.python.org/pypi/gogs-client)).
 2. There are several most wanted features in gogs and gogs-client:
    * [ ] fork api 
    * [ ] PR api ([gogs#2253](https://github.com/gitea/gogs/issues/2253))
    * [ ] token api (in client)
    * [ ] repository listing api (not only for current users and orgs)
 3. Features for proxy, private and ssl_verify shouldn't be implemented in service-dependent manner.
 4. Test should be first-class thing. 👍

**Comment by guyzmo** [comment]
for the feature set, go by babysteps:

1. implement first the already working features, like you first did (clone, create, delete, open, list) and consider that the user can copy/paste the token in the configuration file
2. implement the token API as a second step, the best way would be for you to send a PR to gogs-client for them to integrate it, so then git-repo can merge it in!
3. add the extra stuff we might want to have… You could make a PR to gogs to integrate the fork API, we can 🤞 that PR api lands soon… or you could implement some web scrapping (either in gogs-client or in a third part library extending gogs-client) to support those features.

About the configuration features:

- `ssl_verify` is already implemented and I'm merging it in develop, just look for `self.insecure` on `RepositoryService`,
- `proxy` support is a good thing to have (using the `.gitconfig` proxy setting), and I believe it's a good case for a new issue and PR, adding it for the four services.
- `private` should be a command line argument `git gogs foo/bar create --private`. And there's already an issue to discuss default configuration implementation, but it's not a priority currently.

About the tests, I did my best to make them easy to write and run, of course I'm around if you need any help.

**Comment by guyzmo** [comment]
FYI, I actually just checked with a gogs install, I believe it's possible to make a fork, given that the token auth works for this use case:

if you make a `POST` request with form data containing:

* `uid` → id of the new owner, i.e. current user
* `repo_name` → new name of the repository
* ``
* `description` → description of what is that repository

to the URL: `/repo/fork/{id of the repository to fork}` that should work!

**Comment by pyhedgehog** [comment]
Just to log here results of our discussion:
 1. New version of PR should use third-party library (possibly [gogs-client](https://pypi.python.org/pypi/gogs-client)).
 2. There are several most wanted features in gogs and gogs-client:
    * [ ] fork api ([gogs#1692](https://github.com/gogits/gogs/issues/1692#issuecomment-268494219), [gitea#64](https://github.com/go-gitea/gitea/issues/64))
    * [ ] PR api ([gogs#2253](https://github.com/gitea/gogs/issues/2253))
    * [ ] token api (in client)
    * [ ] repository listing api (not only for current users and orgs)
 3. Features for proxy, private and ssl_verify shouldn't be implemented in service-dependent manner.
 4. Test should be first-class thing. 👍

**Comment by guyzmo** [comment]
implementation for tokens in progress over unfoldingWord-dev/python-gogs-client#2 👍

**Comment by guyzmo** [comment]
BTW, in the module [http_utils](https://github.com/unfoldingWord-dev/python-gogs-client/blob/master/gogs_client/_implementation/http_utils.py#L9) you'll have to have init create a `requests.Session` object and replace all `requests` calls with it. The patch should be fairly straightforward.

Also, we need to make sure that `RelativeHttpRequestor` (or the requests session within) is a singleton instance across the API lib.

That's very important to have that in order to be able to write tests in git-repo.

**Comment by pyhedgehog** [comment]
@guyzmo
> if you make a POST request ... to the URL: /repo/fork/{id of the repository to fork} that should work!

How you've avoided `Bad Request: no CSRF token present` result?

**Comment by bkcsoft** [comment]
> There are several most wanted features in gogs

@pyhedgehog Please make an issue for each (unless there already is one) so that the devs /myself included) are aware of the need 🙂

**Comment by guyzmo** [comment]
@bkcsoft well the two most important missing APIs (AFAICT):

- fork a repository: gogits/gogs#3979
- create a pull request: gogits/gogs#2253
  - one feature is very important to have is the ability to expose pull requests as git refs that can be fetched (on github it's like `git fetch github pull/42/head`).

and generally for feature completeness:

- The snippet feature would be nice as well: gogits/gogs#936

I'll leave @pyhedgehog make an issue about repository listing, as I'm not sure to the details of the repository listing limitations. Some other API might be nice to have (like the ability to list and push SSH public keys, or have oauth2 authentication).
